// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_enum.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CsProtobuf {

  /// <summary>Holder for reflection information generated from cs_enum.proto</summary>
  public static partial class CsEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for cs_enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CsEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1jc19lbnVtLnByb3RvEgtjc19wcm90b2J1ZipFCghFbm1DbWRJRBITCg9D",
            "U19MT0dJTl9VTlVTRUQQABIRCgxDU19MT0dJTl9SRVEQkU4SEQoMQ1NfTE9H",
            "SU5fUkVTEJJOKoABCghQbGF5ZXJJRBIRCg1DU19QTEFZRVJfT05FEAASEQoN",
            "Q1NfUExBWUVSX1RXTxABEhMKD0NTX1BMQVlFUl9USFJFRRACEhIKDkNTX1BM",
            "QVlFUl9GT1VSEAMSEgoOQ1NfUExBWUVSX0ZJVkUQBBIRCg1DU19QTEFZRVJf",
            "U0lYEAUqVwoNQ2FyZEF0dHJpYnV0ZRIRCg1DU19DQVJEX01BWEhQEAASDwoL",
            "Q1NfQ0FSRF9BVEsQARIPCgtDU19DQVJEX0RFRhACEhEKDUNTX0NBUkRfU1BF",
            "RUQQAyozCgdBdGtUeXBlEhIKDkNTX0FUS1RZUEVfQVRLEAASFAoQQ1NfQVRL",
            "VFlQRV9TS0lMTBABKi4KBUNhbXBzEhIKDkNTX0NBTVBfUExBWUVSEAASEQoN",
            "Q1NfQ0FNUF9FTkVNWRABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CsProtobuf.EnmCmdID), typeof(global::CsProtobuf.PlayerID), typeof(global::CsProtobuf.CardAttribute), typeof(global::CsProtobuf.AtkType), typeof(global::CsProtobuf.Camps), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EnmCmdID {
    /// <summary>
    ///proto3中枚举第一个值必须为0
    /// </summary>
    [pbr::OriginalName("CS_LOGIN_UNUSED")] CsLoginUnused = 0,
    /// <summary>
    ///登录请求协议号
    /// </summary>
    [pbr::OriginalName("CS_LOGIN_REQ")] CsLoginReq = 10001,
    /// <summary>
    ///登录请求回包协议号
    /// </summary>
    [pbr::OriginalName("CS_LOGIN_RES")] CsLoginRes = 10002,
  }

  /// <summary>
  ///玩家唯一标识符
  /// </summary>
  public enum PlayerID {
    /// <summary>
    ///头号玩家
    /// </summary>
    [pbr::OriginalName("CS_PLAYER_ONE")] CsPlayerOne = 0,
    [pbr::OriginalName("CS_PLAYER_TWO")] CsPlayerTwo = 1,
    [pbr::OriginalName("CS_PLAYER_THREE")] CsPlayerThree = 2,
    [pbr::OriginalName("CS_PLAYER_FOUR")] CsPlayerFour = 3,
    [pbr::OriginalName("CS_PLAYER_FIVE")] CsPlayerFive = 4,
    [pbr::OriginalName("CS_PLAYER_SIX")] CsPlayerSix = 5,
  }

  /// <summary>
  ///卡牌基本属性
  /// </summary>
  public enum CardAttribute {
    [pbr::OriginalName("CS_CARD_MAXHP")] CsCardMaxhp = 0,
    [pbr::OriginalName("CS_CARD_ATK")] CsCardAtk = 1,
    [pbr::OriginalName("CS_CARD_DEF")] CsCardDef = 2,
    [pbr::OriginalName("CS_CARD_SPEED")] CsCardSpeed = 3,
  }

  /// <summary>
  ///卡牌攻击方式
  /// </summary>
  public enum AtkType {
    /// <summary>
    ///普通攻击
    /// </summary>
    [pbr::OriginalName("CS_ATKTYPE_ATK")] CsAtktypeAtk = 0,
    /// <summary>
    ///释放技能
    /// </summary>
    [pbr::OriginalName("CS_ATKTYPE_SKILL")] CsAtktypeSkill = 1,
  }

  /// <summary>
  ///对战双方标识符
  /// </summary>
  public enum Camps {
    [pbr::OriginalName("CS_CAMP_PLAYER")] CsCampPlayer = 0,
    [pbr::OriginalName("CS_CAMP_ENEMY")] CsCampEnemy = 1,
  }

  #endregion

}

#endregion Designer generated code
