// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_msg.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CsProtobuf {

  /// <summary>Holder for reflection information generated from cs_msg.proto</summary>
  public static partial class CsMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for cs_msg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CsMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjc19tc2cucHJvdG8SC2NzX3Byb3RvYnVmGh1nb29nbGUvcHJvdG9idWYv",
            "Y3NfZW51bS5wcm90byLgAQoHTXNnUGFjaxIlCgdtc2dUeXBlGAEgASgOMhQu",
            "Y3NfcHJvdG9idWYuTXNnVHlwZRImCgdtc2dGcm9tGAIgASgOMhUuY3NfcHJv",
            "dG9idWYuUGxheWVySUQSJAoFbXNnVG8YAyABKA4yFS5jc19wcm90b2J1Zi5Q",
            "bGF5ZXJJRBIvCgxpbml0SXRlbVBhY2sYBCABKAsyGS5jc19wcm90b2J1Zi5J",
            "bml0SXRlbVBhY2sSLwoJZ3JvdXBQYWNrGAUgASgLMhwuY3NfcHJvdG9idWYu",
            "QmF0dGxlR3JvdXBQYWNrIm4KB0NhcmRNc2cSDQoFbWF4SHAYASABKAISCwoD",
            "YXRrGAIgASgCEgsKA2RlZhgDIAEoAhINCgVzcGVlZBgEIAEoAhIKCgJpZBgF",
            "IAEoBRIOCgZpc0Jvcm4YBiABKAgSDwoHYm9yblBvcxgHIAEoBSKSAQoIQ2Ft",
            "cEluZm8SJwoIcGxheWVySUQYASABKA4yFS5jc19wcm90b2J1Zi5QbGF5ZXJJ",
            "RBIgCgRjYW1wGAIgASgOMhIuY3NfcHJvdG9idWYuQ2FtcHMSEgoKaXRlbXND",
            "b3VudBgDIAEoBRInCgljYXJkSXRlbXMYBCADKAsyFC5jc19wcm90b2J1Zi5D",
            "YXJkTXNnIjgKDEluaXRJdGVtUGFjaxIoCgljYW1wSW5mb3MYASADKAsyFS5j",
            "c19wcm90b2J1Zi5DYW1wSW5mbyJvCg9BdHRyaWJ1dGVSZXN1bHQSIAoEY2Ft",
            "cBgBIAEoDjISLmNzX3Byb3RvYnVmLkNhbXBzEisKB3Jlc0F0dHIYAiABKA4y",
            "Gi5jc19wcm90b2J1Zi5DYXJkQXR0cmlidXRlEg0KBXZhbHVlGAMgASgCIlIK",
            "CkFjdGl2ZUl0ZW0SIAoEY2FtcBgBIAEoDjISLmNzX3Byb3RvYnVmLkNhbXBz",
            "EiIKBGNhcmQYAiABKAsyFC5jc19wcm90b2J1Zi5DYXJkTXNnImYKClN0ZXBS",
            "ZXN1bHQSJQoHYXRrVHlwZRgBIAEoDjIULmNzX3Byb3RvYnVmLkF0a1R5cGUS",
            "MQoLYXR0clJlc0xpc3QYAiADKAsyHC5jc19wcm90b2J1Zi5BdHRyaWJ1dGVS",
            "ZXN1bHQiiAEKBFN0ZXASKAoHYXRrSXRlbRgBIAEoCzIXLmNzX3Byb3RvYnVm",
            "LkFjdGl2ZUl0ZW0SKAoHZGVmSXRlbRgCIAEoCzIXLmNzX3Byb3RvYnVmLkFj",
            "dGl2ZUl0ZW0SLAoLc3RlcFJlc0xpc3QYAyADKAsyFy5jc19wcm90b2J1Zi5T",
            "dGVwUmVzdWx0IikKBVJvdW5kEiAKBXN0ZXBzGAEgAygLMhEuY3NfcHJvdG9i",
            "dWYuU3RlcCIOCgxCYXR0bGVSZXN1bHQiZgoPQmF0dGxlR3JvdXBQYWNrEiIK",
            "BnJvdW5kcxgBIAMoCzISLmNzX3Byb3RvYnVmLlJvdW5kEi8KDGJhdHRsZVJl",
            "c3VsdBgCIAEoCzIZLmNzX3Byb3RvYnVmLkJhdHRsZVJlc3VsdCJDCgpCYXR0",
            "bGVQYWNrEjUKD2JhdHRsZUdyb3VwTGlzdBgBIAMoCzIcLmNzX3Byb3RvYnVm",
            "LkJhdHRsZUdyb3VwUGFja2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CsProtobuf.CsEnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.MsgPack), global::CsProtobuf.MsgPack.Parser, new[]{ "MsgType", "MsgFrom", "MsgTo", "InitItemPack", "GroupPack" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.CardMsg), global::CsProtobuf.CardMsg.Parser, new[]{ "MaxHp", "Atk", "Def", "Speed", "Id", "IsBorn", "BornPos" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.CampInfo), global::CsProtobuf.CampInfo.Parser, new[]{ "PlayerID", "Camp", "ItemsCount", "CardItems" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.InitItemPack), global::CsProtobuf.InitItemPack.Parser, new[]{ "CampInfos" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.AttributeResult), global::CsProtobuf.AttributeResult.Parser, new[]{ "Camp", "ResAttr", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.ActiveItem), global::CsProtobuf.ActiveItem.Parser, new[]{ "Camp", "Card" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.StepResult), global::CsProtobuf.StepResult.Parser, new[]{ "AtkType", "AttrResList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.Step), global::CsProtobuf.Step.Parser, new[]{ "AtkItem", "DefItem", "StepResList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.Round), global::CsProtobuf.Round.Parser, new[]{ "Steps" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.BattleResult), global::CsProtobuf.BattleResult.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.BattleGroupPack), global::CsProtobuf.BattleGroupPack.Parser, new[]{ "Rounds", "BattleResult" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CsProtobuf.BattlePack), global::CsProtobuf.BattlePack.Parser, new[]{ "BattleGroupList" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MsgPack : pb::IMessage<MsgPack> {
    private static readonly pb::MessageParser<MsgPack> _parser = new pb::MessageParser<MsgPack>(() => new MsgPack());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgPack(MsgPack other) : this() {
      msgType_ = other.msgType_;
      msgFrom_ = other.msgFrom_;
      msgTo_ = other.msgTo_;
      InitItemPack = other.initItemPack_ != null ? other.InitItemPack.Clone() : null;
      GroupPack = other.groupPack_ != null ? other.GroupPack.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgPack Clone() {
      return new MsgPack(this);
    }

    /// <summary>Field number for the "msgType" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private global::CsProtobuf.MsgType msgType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.MsgType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "msgFrom" field.</summary>
    public const int MsgFromFieldNumber = 2;
    private global::CsProtobuf.PlayerID msgFrom_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.PlayerID MsgFrom {
      get { return msgFrom_; }
      set {
        msgFrom_ = value;
      }
    }

    /// <summary>Field number for the "msgTo" field.</summary>
    public const int MsgToFieldNumber = 3;
    private global::CsProtobuf.PlayerID msgTo_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.PlayerID MsgTo {
      get { return msgTo_; }
      set {
        msgTo_ = value;
      }
    }

    /// <summary>Field number for the "initItemPack" field.</summary>
    public const int InitItemPackFieldNumber = 4;
    private global::CsProtobuf.InitItemPack initItemPack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.InitItemPack InitItemPack {
      get { return initItemPack_; }
      set {
        initItemPack_ = value;
      }
    }

    /// <summary>Field number for the "groupPack" field.</summary>
    public const int GroupPackFieldNumber = 5;
    private global::CsProtobuf.BattleGroupPack groupPack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.BattleGroupPack GroupPack {
      get { return groupPack_; }
      set {
        groupPack_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (MsgFrom != other.MsgFrom) return false;
      if (MsgTo != other.MsgTo) return false;
      if (!object.Equals(InitItemPack, other.InitItemPack)) return false;
      if (!object.Equals(GroupPack, other.GroupPack)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != 0) hash ^= MsgType.GetHashCode();
      if (MsgFrom != 0) hash ^= MsgFrom.GetHashCode();
      if (MsgTo != 0) hash ^= MsgTo.GetHashCode();
      if (initItemPack_ != null) hash ^= InitItemPack.GetHashCode();
      if (groupPack_ != null) hash ^= GroupPack.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MsgType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (MsgFrom != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) MsgFrom);
      }
      if (MsgTo != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MsgTo);
      }
      if (initItemPack_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(InitItemPack);
      }
      if (groupPack_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(GroupPack);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (MsgFrom != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgFrom);
      }
      if (MsgTo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgTo);
      }
      if (initItemPack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitItemPack);
      }
      if (groupPack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GroupPack);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgPack other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != 0) {
        MsgType = other.MsgType;
      }
      if (other.MsgFrom != 0) {
        MsgFrom = other.MsgFrom;
      }
      if (other.MsgTo != 0) {
        MsgTo = other.MsgTo;
      }
      if (other.initItemPack_ != null) {
        if (initItemPack_ == null) {
          initItemPack_ = new global::CsProtobuf.InitItemPack();
        }
        InitItemPack.MergeFrom(other.InitItemPack);
      }
      if (other.groupPack_ != null) {
        if (groupPack_ == null) {
          groupPack_ = new global::CsProtobuf.BattleGroupPack();
        }
        GroupPack.MergeFrom(other.GroupPack);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            msgType_ = (global::CsProtobuf.MsgType) input.ReadEnum();
            break;
          }
          case 16: {
            msgFrom_ = (global::CsProtobuf.PlayerID) input.ReadEnum();
            break;
          }
          case 24: {
            msgTo_ = (global::CsProtobuf.PlayerID) input.ReadEnum();
            break;
          }
          case 34: {
            if (initItemPack_ == null) {
              initItemPack_ = new global::CsProtobuf.InitItemPack();
            }
            input.ReadMessage(initItemPack_);
            break;
          }
          case 42: {
            if (groupPack_ == null) {
              groupPack_ = new global::CsProtobuf.BattleGroupPack();
            }
            input.ReadMessage(groupPack_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///卡牌
  /// </summary>
  public sealed partial class CardMsg : pb::IMessage<CardMsg> {
    private static readonly pb::MessageParser<CardMsg> _parser = new pb::MessageParser<CardMsg>(() => new CardMsg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CardMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardMsg(CardMsg other) : this() {
      maxHp_ = other.maxHp_;
      atk_ = other.atk_;
      def_ = other.def_;
      speed_ = other.speed_;
      id_ = other.id_;
      isBorn_ = other.isBorn_;
      bornPos_ = other.bornPos_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardMsg Clone() {
      return new CardMsg(this);
    }

    /// <summary>Field number for the "maxHp" field.</summary>
    public const int MaxHpFieldNumber = 1;
    private float maxHp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float MaxHp {
      get { return maxHp_; }
      set {
        maxHp_ = value;
      }
    }

    /// <summary>Field number for the "atk" field.</summary>
    public const int AtkFieldNumber = 2;
    private float atk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Atk {
      get { return atk_; }
      set {
        atk_ = value;
      }
    }

    /// <summary>Field number for the "def" field.</summary>
    public const int DefFieldNumber = 3;
    private float def_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Def {
      get { return def_; }
      set {
        def_ = value;
      }
    }

    /// <summary>Field number for the "speed" field.</summary>
    public const int SpeedFieldNumber = 4;
    private float speed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 5;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "isBorn" field.</summary>
    public const int IsBornFieldNumber = 6;
    private bool isBorn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsBorn {
      get { return isBorn_; }
      set {
        isBorn_ = value;
      }
    }

    /// <summary>Field number for the "bornPos" field.</summary>
    public const int BornPosFieldNumber = 7;
    private int bornPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BornPos {
      get { return bornPos_; }
      set {
        bornPos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CardMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CardMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MaxHp != other.MaxHp) return false;
      if (Atk != other.Atk) return false;
      if (Def != other.Def) return false;
      if (Speed != other.Speed) return false;
      if (Id != other.Id) return false;
      if (IsBorn != other.IsBorn) return false;
      if (BornPos != other.BornPos) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MaxHp != 0F) hash ^= MaxHp.GetHashCode();
      if (Atk != 0F) hash ^= Atk.GetHashCode();
      if (Def != 0F) hash ^= Def.GetHashCode();
      if (Speed != 0F) hash ^= Speed.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (IsBorn != false) hash ^= IsBorn.GetHashCode();
      if (BornPos != 0) hash ^= BornPos.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MaxHp != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(MaxHp);
      }
      if (Atk != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Atk);
      }
      if (Def != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Def);
      }
      if (Speed != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Speed);
      }
      if (Id != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Id);
      }
      if (IsBorn != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsBorn);
      }
      if (BornPos != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(BornPos);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MaxHp != 0F) {
        size += 1 + 4;
      }
      if (Atk != 0F) {
        size += 1 + 4;
      }
      if (Def != 0F) {
        size += 1 + 4;
      }
      if (Speed != 0F) {
        size += 1 + 4;
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (IsBorn != false) {
        size += 1 + 1;
      }
      if (BornPos != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BornPos);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CardMsg other) {
      if (other == null) {
        return;
      }
      if (other.MaxHp != 0F) {
        MaxHp = other.MaxHp;
      }
      if (other.Atk != 0F) {
        Atk = other.Atk;
      }
      if (other.Def != 0F) {
        Def = other.Def;
      }
      if (other.Speed != 0F) {
        Speed = other.Speed;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.IsBorn != false) {
        IsBorn = other.IsBorn;
      }
      if (other.BornPos != 0) {
        BornPos = other.BornPos;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            MaxHp = input.ReadFloat();
            break;
          }
          case 21: {
            Atk = input.ReadFloat();
            break;
          }
          case 29: {
            Def = input.ReadFloat();
            break;
          }
          case 37: {
            Speed = input.ReadFloat();
            break;
          }
          case 40: {
            Id = input.ReadInt32();
            break;
          }
          case 48: {
            IsBorn = input.ReadBool();
            break;
          }
          case 56: {
            BornPos = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///初始化消息包
  /// </summary>
  public sealed partial class CampInfo : pb::IMessage<CampInfo> {
    private static readonly pb::MessageParser<CampInfo> _parser = new pb::MessageParser<CampInfo>(() => new CampInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CampInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CampInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CampInfo(CampInfo other) : this() {
      playerID_ = other.playerID_;
      camp_ = other.camp_;
      itemsCount_ = other.itemsCount_;
      cardItems_ = other.cardItems_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CampInfo Clone() {
      return new CampInfo(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private global::CsProtobuf.PlayerID playerID_ = 0;
    /// <summary>
    ///身份
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.PlayerID PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "camp" field.</summary>
    public const int CampFieldNumber = 2;
    private global::CsProtobuf.Camps camp_ = 0;
    /// <summary>
    ///对战阵营
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.Camps Camp {
      get { return camp_; }
      set {
        camp_ = value;
      }
    }

    /// <summary>Field number for the "itemsCount" field.</summary>
    public const int ItemsCountFieldNumber = 3;
    private int itemsCount_;
    /// <summary>
    ///卡牌数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemsCount {
      get { return itemsCount_; }
      set {
        itemsCount_ = value;
      }
    }

    /// <summary>Field number for the "cardItems" field.</summary>
    public const int CardItemsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::CsProtobuf.CardMsg> _repeated_cardItems_codec
        = pb::FieldCodec.ForMessage(34, global::CsProtobuf.CardMsg.Parser);
    private readonly pbc::RepeatedField<global::CsProtobuf.CardMsg> cardItems_ = new pbc::RepeatedField<global::CsProtobuf.CardMsg>();
    /// <summary>
    ///卡牌数组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CsProtobuf.CardMsg> CardItems {
      get { return cardItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CampInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CampInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if (Camp != other.Camp) return false;
      if (ItemsCount != other.ItemsCount) return false;
      if(!cardItems_.Equals(other.cardItems_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (Camp != 0) hash ^= Camp.GetHashCode();
      if (ItemsCount != 0) hash ^= ItemsCount.GetHashCode();
      hash ^= cardItems_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerID != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PlayerID);
      }
      if (Camp != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Camp);
      }
      if (ItemsCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ItemsCount);
      }
      cardItems_.WriteTo(output, _repeated_cardItems_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerID);
      }
      if (Camp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Camp);
      }
      if (ItemsCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemsCount);
      }
      size += cardItems_.CalculateSize(_repeated_cardItems_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CampInfo other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.Camp != 0) {
        Camp = other.Camp;
      }
      if (other.ItemsCount != 0) {
        ItemsCount = other.ItemsCount;
      }
      cardItems_.Add(other.cardItems_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            playerID_ = (global::CsProtobuf.PlayerID) input.ReadEnum();
            break;
          }
          case 16: {
            camp_ = (global::CsProtobuf.Camps) input.ReadEnum();
            break;
          }
          case 24: {
            ItemsCount = input.ReadInt32();
            break;
          }
          case 34: {
            cardItems_.AddEntriesFrom(input, _repeated_cardItems_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class InitItemPack : pb::IMessage<InitItemPack> {
    private static readonly pb::MessageParser<InitItemPack> _parser = new pb::MessageParser<InitItemPack>(() => new InitItemPack());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InitItemPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InitItemPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InitItemPack(InitItemPack other) : this() {
      campInfos_ = other.campInfos_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InitItemPack Clone() {
      return new InitItemPack(this);
    }

    /// <summary>Field number for the "campInfos" field.</summary>
    public const int CampInfosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CsProtobuf.CampInfo> _repeated_campInfos_codec
        = pb::FieldCodec.ForMessage(10, global::CsProtobuf.CampInfo.Parser);
    private readonly pbc::RepeatedField<global::CsProtobuf.CampInfo> campInfos_ = new pbc::RepeatedField<global::CsProtobuf.CampInfo>();
    /// <summary>
    ///阵营列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CsProtobuf.CampInfo> CampInfos {
      get { return campInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InitItemPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InitItemPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!campInfos_.Equals(other.campInfos_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= campInfos_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      campInfos_.WriteTo(output, _repeated_campInfos_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += campInfos_.CalculateSize(_repeated_campInfos_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InitItemPack other) {
      if (other == null) {
        return;
      }
      campInfos_.Add(other.campInfos_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            campInfos_.AddEntriesFrom(input, _repeated_campInfos_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///对属性值的结果
  /// </summary>
  public sealed partial class AttributeResult : pb::IMessage<AttributeResult> {
    private static readonly pb::MessageParser<AttributeResult> _parser = new pb::MessageParser<AttributeResult>(() => new AttributeResult());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AttributeResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttributeResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttributeResult(AttributeResult other) : this() {
      camp_ = other.camp_;
      resAttr_ = other.resAttr_;
      value_ = other.value_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttributeResult Clone() {
      return new AttributeResult(this);
    }

    /// <summary>Field number for the "camp" field.</summary>
    public const int CampFieldNumber = 1;
    private global::CsProtobuf.Camps camp_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.Camps Camp {
      get { return camp_; }
      set {
        camp_ = value;
      }
    }

    /// <summary>Field number for the "resAttr" field.</summary>
    public const int ResAttrFieldNumber = 2;
    private global::CsProtobuf.CardAttribute resAttr_ = 0;
    /// <summary>
    ///变更属性
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.CardAttribute ResAttr {
      get { return resAttr_; }
      set {
        resAttr_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private float value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AttributeResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AttributeResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Camp != other.Camp) return false;
      if (ResAttr != other.ResAttr) return false;
      if (Value != other.Value) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Camp != 0) hash ^= Camp.GetHashCode();
      if (ResAttr != 0) hash ^= ResAttr.GetHashCode();
      if (Value != 0F) hash ^= Value.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Camp != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Camp);
      }
      if (ResAttr != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ResAttr);
      }
      if (Value != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Value);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Camp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Camp);
      }
      if (ResAttr != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResAttr);
      }
      if (Value != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AttributeResult other) {
      if (other == null) {
        return;
      }
      if (other.Camp != 0) {
        Camp = other.Camp;
      }
      if (other.ResAttr != 0) {
        ResAttr = other.ResAttr;
      }
      if (other.Value != 0F) {
        Value = other.Value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            camp_ = (global::CsProtobuf.Camps) input.ReadEnum();
            break;
          }
          case 16: {
            resAttr_ = (global::CsProtobuf.CardAttribute) input.ReadEnum();
            break;
          }
          case 29: {
            Value = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///每步中的活跃卡牌
  /// </summary>
  public sealed partial class ActiveItem : pb::IMessage<ActiveItem> {
    private static readonly pb::MessageParser<ActiveItem> _parser = new pb::MessageParser<ActiveItem>(() => new ActiveItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActiveItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActiveItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActiveItem(ActiveItem other) : this() {
      camp_ = other.camp_;
      Card = other.card_ != null ? other.Card.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActiveItem Clone() {
      return new ActiveItem(this);
    }

    /// <summary>Field number for the "camp" field.</summary>
    public const int CampFieldNumber = 1;
    private global::CsProtobuf.Camps camp_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.Camps Camp {
      get { return camp_; }
      set {
        camp_ = value;
      }
    }

    /// <summary>Field number for the "card" field.</summary>
    public const int CardFieldNumber = 2;
    private global::CsProtobuf.CardMsg card_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.CardMsg Card {
      get { return card_; }
      set {
        card_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActiveItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActiveItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Camp != other.Camp) return false;
      if (!object.Equals(Card, other.Card)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Camp != 0) hash ^= Camp.GetHashCode();
      if (card_ != null) hash ^= Card.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Camp != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Camp);
      }
      if (card_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Card);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Camp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Camp);
      }
      if (card_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Card);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActiveItem other) {
      if (other == null) {
        return;
      }
      if (other.Camp != 0) {
        Camp = other.Camp;
      }
      if (other.card_ != null) {
        if (card_ == null) {
          card_ = new global::CsProtobuf.CardMsg();
        }
        Card.MergeFrom(other.Card);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            camp_ = (global::CsProtobuf.Camps) input.ReadEnum();
            break;
          }
          case 18: {
            if (card_ == null) {
              card_ = new global::CsProtobuf.CardMsg();
            }
            input.ReadMessage(card_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///每步结果
  /// </summary>
  public sealed partial class StepResult : pb::IMessage<StepResult> {
    private static readonly pb::MessageParser<StepResult> _parser = new pb::MessageParser<StepResult>(() => new StepResult());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StepResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StepResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StepResult(StepResult other) : this() {
      atkType_ = other.atkType_;
      attrResList_ = other.attrResList_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StepResult Clone() {
      return new StepResult(this);
    }

    /// <summary>Field number for the "atkType" field.</summary>
    public const int AtkTypeFieldNumber = 1;
    private global::CsProtobuf.AtkType atkType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.AtkType AtkType {
      get { return atkType_; }
      set {
        atkType_ = value;
      }
    }

    /// <summary>Field number for the "attrResList" field.</summary>
    public const int AttrResListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CsProtobuf.AttributeResult> _repeated_attrResList_codec
        = pb::FieldCodec.ForMessage(18, global::CsProtobuf.AttributeResult.Parser);
    private readonly pbc::RepeatedField<global::CsProtobuf.AttributeResult> attrResList_ = new pbc::RepeatedField<global::CsProtobuf.AttributeResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CsProtobuf.AttributeResult> AttrResList {
      get { return attrResList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StepResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StepResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AtkType != other.AtkType) return false;
      if(!attrResList_.Equals(other.attrResList_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AtkType != 0) hash ^= AtkType.GetHashCode();
      hash ^= attrResList_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AtkType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AtkType);
      }
      attrResList_.WriteTo(output, _repeated_attrResList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AtkType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AtkType);
      }
      size += attrResList_.CalculateSize(_repeated_attrResList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StepResult other) {
      if (other == null) {
        return;
      }
      if (other.AtkType != 0) {
        AtkType = other.AtkType;
      }
      attrResList_.Add(other.attrResList_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            atkType_ = (global::CsProtobuf.AtkType) input.ReadEnum();
            break;
          }
          case 18: {
            attrResList_.AddEntriesFrom(input, _repeated_attrResList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///回合中的每"步"
  /// </summary>
  public sealed partial class Step : pb::IMessage<Step> {
    private static readonly pb::MessageParser<Step> _parser = new pb::MessageParser<Step>(() => new Step());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Step> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Step() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Step(Step other) : this() {
      AtkItem = other.atkItem_ != null ? other.AtkItem.Clone() : null;
      DefItem = other.defItem_ != null ? other.DefItem.Clone() : null;
      stepResList_ = other.stepResList_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Step Clone() {
      return new Step(this);
    }

    /// <summary>Field number for the "atkItem" field.</summary>
    public const int AtkItemFieldNumber = 1;
    private global::CsProtobuf.ActiveItem atkItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.ActiveItem AtkItem {
      get { return atkItem_; }
      set {
        atkItem_ = value;
      }
    }

    /// <summary>Field number for the "defItem" field.</summary>
    public const int DefItemFieldNumber = 2;
    private global::CsProtobuf.ActiveItem defItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.ActiveItem DefItem {
      get { return defItem_; }
      set {
        defItem_ = value;
      }
    }

    /// <summary>Field number for the "stepResList" field.</summary>
    public const int StepResListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CsProtobuf.StepResult> _repeated_stepResList_codec
        = pb::FieldCodec.ForMessage(26, global::CsProtobuf.StepResult.Parser);
    private readonly pbc::RepeatedField<global::CsProtobuf.StepResult> stepResList_ = new pbc::RepeatedField<global::CsProtobuf.StepResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CsProtobuf.StepResult> StepResList {
      get { return stepResList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Step);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Step other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AtkItem, other.AtkItem)) return false;
      if (!object.Equals(DefItem, other.DefItem)) return false;
      if(!stepResList_.Equals(other.stepResList_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (atkItem_ != null) hash ^= AtkItem.GetHashCode();
      if (defItem_ != null) hash ^= DefItem.GetHashCode();
      hash ^= stepResList_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (atkItem_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AtkItem);
      }
      if (defItem_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DefItem);
      }
      stepResList_.WriteTo(output, _repeated_stepResList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (atkItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AtkItem);
      }
      if (defItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DefItem);
      }
      size += stepResList_.CalculateSize(_repeated_stepResList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Step other) {
      if (other == null) {
        return;
      }
      if (other.atkItem_ != null) {
        if (atkItem_ == null) {
          atkItem_ = new global::CsProtobuf.ActiveItem();
        }
        AtkItem.MergeFrom(other.AtkItem);
      }
      if (other.defItem_ != null) {
        if (defItem_ == null) {
          defItem_ = new global::CsProtobuf.ActiveItem();
        }
        DefItem.MergeFrom(other.DefItem);
      }
      stepResList_.Add(other.stepResList_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (atkItem_ == null) {
              atkItem_ = new global::CsProtobuf.ActiveItem();
            }
            input.ReadMessage(atkItem_);
            break;
          }
          case 18: {
            if (defItem_ == null) {
              defItem_ = new global::CsProtobuf.ActiveItem();
            }
            input.ReadMessage(defItem_);
            break;
          }
          case 26: {
            stepResList_.AddEntriesFrom(input, _repeated_stepResList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///回合
  /// </summary>
  public sealed partial class Round : pb::IMessage<Round> {
    private static readonly pb::MessageParser<Round> _parser = new pb::MessageParser<Round>(() => new Round());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Round> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Round() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Round(Round other) : this() {
      steps_ = other.steps_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Round Clone() {
      return new Round(this);
    }

    /// <summary>Field number for the "steps" field.</summary>
    public const int StepsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CsProtobuf.Step> _repeated_steps_codec
        = pb::FieldCodec.ForMessage(10, global::CsProtobuf.Step.Parser);
    private readonly pbc::RepeatedField<global::CsProtobuf.Step> steps_ = new pbc::RepeatedField<global::CsProtobuf.Step>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CsProtobuf.Step> Steps {
      get { return steps_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Round);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Round other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!steps_.Equals(other.steps_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= steps_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      steps_.WriteTo(output, _repeated_steps_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += steps_.CalculateSize(_repeated_steps_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Round other) {
      if (other == null) {
        return;
      }
      steps_.Add(other.steps_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            steps_.AddEntriesFrom(input, _repeated_steps_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///本组对战结果
  /// </summary>
  public sealed partial class BattleResult : pb::IMessage<BattleResult> {
    private static readonly pb::MessageParser<BattleResult> _parser = new pb::MessageParser<BattleResult>(() => new BattleResult());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattleResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleResult(BattleResult other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleResult Clone() {
      return new BattleResult(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattleResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattleResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattleResult other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  ///对战组
  /// </summary>
  public sealed partial class BattleGroupPack : pb::IMessage<BattleGroupPack> {
    private static readonly pb::MessageParser<BattleGroupPack> _parser = new pb::MessageParser<BattleGroupPack>(() => new BattleGroupPack());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattleGroupPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleGroupPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleGroupPack(BattleGroupPack other) : this() {
      rounds_ = other.rounds_.Clone();
      BattleResult = other.battleResult_ != null ? other.BattleResult.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleGroupPack Clone() {
      return new BattleGroupPack(this);
    }

    /// <summary>Field number for the "rounds" field.</summary>
    public const int RoundsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CsProtobuf.Round> _repeated_rounds_codec
        = pb::FieldCodec.ForMessage(10, global::CsProtobuf.Round.Parser);
    private readonly pbc::RepeatedField<global::CsProtobuf.Round> rounds_ = new pbc::RepeatedField<global::CsProtobuf.Round>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CsProtobuf.Round> Rounds {
      get { return rounds_; }
    }

    /// <summary>Field number for the "battleResult" field.</summary>
    public const int BattleResultFieldNumber = 2;
    private global::CsProtobuf.BattleResult battleResult_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CsProtobuf.BattleResult BattleResult {
      get { return battleResult_; }
      set {
        battleResult_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattleGroupPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattleGroupPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rounds_.Equals(other.rounds_)) return false;
      if (!object.Equals(BattleResult, other.BattleResult)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rounds_.GetHashCode();
      if (battleResult_ != null) hash ^= BattleResult.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      rounds_.WriteTo(output, _repeated_rounds_codec);
      if (battleResult_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BattleResult);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += rounds_.CalculateSize(_repeated_rounds_codec);
      if (battleResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleResult);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattleGroupPack other) {
      if (other == null) {
        return;
      }
      rounds_.Add(other.rounds_);
      if (other.battleResult_ != null) {
        if (battleResult_ == null) {
          battleResult_ = new global::CsProtobuf.BattleResult();
        }
        BattleResult.MergeFrom(other.BattleResult);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            rounds_.AddEntriesFrom(input, _repeated_rounds_codec);
            break;
          }
          case 18: {
            if (battleResult_ == null) {
              battleResult_ = new global::CsProtobuf.BattleResult();
            }
            input.ReadMessage(battleResult_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class BattlePack : pb::IMessage<BattlePack> {
    private static readonly pb::MessageParser<BattlePack> _parser = new pb::MessageParser<BattlePack>(() => new BattlePack());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattlePack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CsProtobuf.CsMsgReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePack(BattlePack other) : this() {
      battleGroupList_ = other.battleGroupList_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePack Clone() {
      return new BattlePack(this);
    }

    /// <summary>Field number for the "battleGroupList" field.</summary>
    public const int BattleGroupListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CsProtobuf.BattleGroupPack> _repeated_battleGroupList_codec
        = pb::FieldCodec.ForMessage(10, global::CsProtobuf.BattleGroupPack.Parser);
    private readonly pbc::RepeatedField<global::CsProtobuf.BattleGroupPack> battleGroupList_ = new pbc::RepeatedField<global::CsProtobuf.BattleGroupPack>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CsProtobuf.BattleGroupPack> BattleGroupList {
      get { return battleGroupList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattlePack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattlePack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!battleGroupList_.Equals(other.battleGroupList_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= battleGroupList_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      battleGroupList_.WriteTo(output, _repeated_battleGroupList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += battleGroupList_.CalculateSize(_repeated_battleGroupList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattlePack other) {
      if (other == null) {
        return;
      }
      battleGroupList_.Add(other.battleGroupList_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            battleGroupList_.AddEntriesFrom(input, _repeated_battleGroupList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
